apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-with-metrics-svcmon
spec:
  selector:
    matchLabels:
      app: nginx-with-metrics-svc
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: metrics