repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com
  - name: jetstack
    url: https://charts.jetstack.io
  - name: harbor
    url: https://helm.goharbor.iom

releases:
  - name: nginx-ingress
    namespace: nginx-ingress
    createNamespace: true
    chart: stable/nginx-ingress
    version: 1.11.1

  - name: cert-manager
    namespace: cert-manager
    createNamespace: true
    chart: jetstack/cert-manager
    version: v0.15.1
    set:
      - name: installCRDs
        value: true

#finish later. how to create Issuer? exetute kubectl... or separate heml installation ?

  - name: harbor
    namespace: harbor
    createNamespace: true
    chart: harbor/harbor
    version: 1.1.2
    values:
      - harbor-values.yaml
