apiVersion: v1
kind: Service
metadata:
  name: paymentservice
  labels:
    name: paymentservice
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    name: paymentservice
    #change version to green
    version: blue
  type: LoadBalancer