apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice-blue
  labels:
    app: paymentservice
    version: blue
spec:
  selector:
    matchLabels:
      app: paymentservice


  replicas: 3
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
        - name: server
          image: dimpon/hipster-paymentservice:1.0

          env:
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: "productcatalogservice:3550"
            - name: CURRENCY_SERVICE_ADDR
              value: "currencyservice:7000"
            - name: CART_SERVICE_ADDR
              value: "cartservice:7070"
            - name: RECOMMENDATION_SERVICE_ADDR
              value: "recommendationservice:8080"
            - name: SHIPPING_SERVICE_ADDR
              value: "shippingservice:50051"
            - name: CHECKOUT_SERVICE_ADDR
              value: "checkoutservice:5050"
            - name: AD_SERVICE_ADDR
              value: "adservice:9555"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice-green
  labels:
    app: paymentservice
    version: green
spec:
  selector:
    matchLabels:
      app: paymentservice

  replicas: 0
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
        - name: server
          image: dimpon/hipster-paymentservice:2.0

          env:
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: "productcatalogservice:3550"
            - name: CURRENCY_SERVICE_ADDR
              value: "currencyservice:7000"
            - name: CART_SERVICE_ADDR
              value: "cartservice:7070"
            - name: RECOMMENDATION_SERVICE_ADDR
              value: "recommendationservice:8080"
            - name: SHIPPING_SERVICE_ADDR
              value: "shippingservice:50051"
            - name: CHECKOUT_SERVICE_ADDR
              value: "checkoutservice:5050"


