apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: dogs.example.dimpon.com
spec:
  group: example.dimpon.com
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: dogs
    singular: dog
    kind: Dog
    shortNames:
      - dog
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            owner:
              type: string

  # subresources describes the subresources for custom resources.
  subresources:
    # status enables the status subresource.
    status: {}
