backend:
  type: es
  es:
    host: elasticsearch-master
    #time_key: "@timestamp_fb"
    #logstash_format: "Off"

tolerations:
  - key: node-role
    operator: Equal
    value: infra
    effect: NoSchedule

nodeSelector:
  cloud.google.com/gke-nodepool: infra-pool

rawConfig: |
  @INCLUDE fluent-bit-service.conf
  @INCLUDE fluent-bit-input.conf
  @INCLUDE fluent-bit-filter.conf
  @INCLUDE fluent-bit-output.conf
  [FILTER]
    Name modify
    Match *
    Remove time
    Remove @timestamp
