grafana:
  enabled: true
  adminPassword: xxxxx

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    path: /
    hosts:
      - grafana.35.193.244.77.xip.io

  additionalDataSources:
    - name: Loki
      type: loki
      url: http://loki:3100/
      access: proxy

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    path: /
    hosts:
      - prometheus.35.193.244.77.xip.io

additionalPrometheusRules:
  - name: additional-prometheus-rules
    groups:
      - name: elasticsearch
        rules:
          - alert: ElasticsearchTooFewNodesRunning
            expr: elasticsearch_cluster_health_number_of_nodes < 3
            for: 5m
            labels:
              severity: critical
            annotations:
              description: There are only {{$value}} < 3 ElasticSearch nodes running
              summary: ElasticSearch running on less than 3 nodes

